services:
    api:
        build: backend
        env_file: backend/.env
        environment:
            - PGHOST=postgres
        ports:
            - "4500:4000"
        depends_on:
            - postgres
    gui:
        build: webapp
        ports:
            - "8080:80"
    postgres:
        image: "postgres"
        restart: always
        command: -p 5800
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5800:5800"
        volumes:
            - ./database/data:/var/lib/postgresql/data/
            - ./database/seed.sql:/docker-entrypoint-initdb.d/create_tables.sql
